# Python CircleCI 2.0 configuration file
version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: AUTH
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m pytest -v

      - run:
          context: AUTH
          name: Environment Variables
          command: |
            echo "$DOCKER_USER"

      - run:
          context: AUTH
          name: Environment Variables 2
          command: |
            echo $DOCKER_USER

      - run:
          name: Environment Variables 3
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS

      - run:
          name: Environment Variables 4
          command: |
            docker build -t mariusz-cichy/cicd-buzz:$CIRCLE_BRANCH .
            docker mariusz-cichy/cicd-buzz:$CIRCLE_BRANCH