# Python CircleCI 2.0 configuration file
version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: AUTH
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      # Step 2: create virtual env and install dependencies
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m pytest -v

      - run:
          name: Build docker and push to Docker Hub
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASS
            docker build -t emcea/cicd-buzz:$CIRCLE_BRANCH .
            docker push emcea/cicd-buzz:$CIRCLE_BRANCH

      - run:
          name: Push to Heroku
          command: |
            wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
            heroku container:login
            heroku container:push web --app $HEROKU_APP_NAME
            heroku container:release web --app $HEROKU_APP_NAME